name: GitHub release

on:
  schedule:
    - cron: '50 * * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Docker build
        run: docker-compose build github-release

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist github-release cp -rfv ./dist/* /dist

      - name: Create release
        run: gh release create v$( date +%Y-%m-%d-%H-%M ) $(pwd)/dist/*
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
